apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001 
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /NDM 
    server: 192.168.110.225 
  persistentVolumeReclaimPolicy: Recycle 
